### ISSUE TITLE
package names incorrect

### ISSUE THREAD

**Issue by supertick** [hdinsight/storm-eventhubs#1]
It looks like someone changed all the package names without changing the file structure, which of course prevents the code from even compiling.
I've been looking for a viable Storm 9.3 Spout in Java for several days, and was hoping this might be it since it appears to be microsoft checkin.

**Comment by ravitandonrt** [comment]
Hey @supertick, I had fixed this issue as part of this commit: https://github.com/hdinsight/storm-eventhubs/commit/fb31d9f7be106a0bb27cd169d2f6402c25e90f14

Are you still hitting issues with compiling?

I have been successfully using the jar built from this repo with our Storm examples here: https://github.com/hdinsight/hdinsight-storm-examples/tree/master/lib/eventhubs

**Comment by ravitandonrt** [comment]
@supertick I am going to close this issue assuming this is addressed, if it is not please let us know.
